version: "3"
services:
  conan:
    build : .
    container_name: mosaiq-conan-server
    networks:
      static-network:
        ipv4_address: 172.20.0.5
    volumes:
      - ./conan:/var/lib/conan
    ports:
      - "9300:9300"
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16

 
